LogoVote : add registLogo testcase
EtherTW/Smart-contracts pull request #6
Opened 2017-05-28 11:06 UTC by y12studio

2017-05-28 12:49 UTC, y12studio commented on LogoVote/truffle/contracts/LogoVote.sol
> +	function claimRewardV1 (address _receiver) stopInEmergency afterEnd {
@willliw  Does it really need to keep this old version ?

2017-05-28 13:06 UTC, willliw commented on LogoVote/truffle/contracts/LogoVote.sol
> +	function claimRewardV1 (address _receiver) stopInEmergency afterEnd {
不用留，這些都是我自己沒merge好, sorry。

2017-05-28 14:49 UTC, y12studio commented
@willliw @ChihChengLiang  Ready for review and merge.

2017-05-28 16:08 UTC, ChihChengLiang requested changes
Awesome works on testing major functions of the contract. Some changes can make the tests look better.

2017-05-28 16:08 UTC, ChihChengLiang commented on LogoVote/truffle/test/logovote.js
> +      assert.isOk(_isLogoResult, 'isLogo shoule be ok')
typo, and another same typo in next assert.

2017-05-28 16:08 UTC, ChihChengLiang commented on LogoVote/truffle/test/logovote.js
> +  it('registLogo should be ok', function () {
`should be ok` is too ambiguous. The sentence could tell more about what this test is doing and what the function *should behave*. So a new developer could understand the function and the test easier.
For example,
```
it('#registLogo() should increase the length of logos array from 0 to 1', ...
```

2017-05-28 16:08 UTC, ChihChengLiang commented on LogoVote/truffle/test/logovote.js
> +      // console.log(_txr)
debug code should not be committed.

2017-05-28 16:08 UTC, ChihChengLiang commented on LogoVote/truffle/test/logovote.js
> +  it('donate should be ok', function () {
example:
`it('should show #totalReward() 6.6 ether after #donate() 1.1, 2.2, and 3.3 ether.')`

2017-05-28 16:08 UTC, ChihChengLiang commented on LogoVote/truffle/test/logovote.js
> +  it('isLogo should be ok', function () {
example:
```
it('#isLogo() should tell if an address is in logos, or not in')
```

2017-05-28 18:17 UTC, willliw commented
utACK

2017-05-28 18:19 UTC, willliw approved these changes

2017-05-29 14:16 UTC, ChihChengLiang approved these changes

2017-05-29 14:20 UTC, merged